version: "3.2"
services:
  aptabase_db:
    container_name: aptabase_db
    image: postgres:15-alpine
    restart: always
    # ports:
    #   - 5432:5432
    volumes:
      - aptabase-db-data:/var/lib/postgresql/data
    networks:
      - aptabase
    environment:
      - POSTGRES_USER=${AUTH_USER}
      - POSTGRES_PASSWORD=${AUTH_PASSWORD}

  aptabase_events_db:
    container_name: aptabase_events_db
    image: clickhouse/clickhouse-server:23.8.4.69-alpine
    restart: always
    # ports:
    #   - 8123:8123    
    volumes:
      - aptabase-events-db-data:/var/lib/clickhouse
    networks:
      - aptabase
    environment:
      - CLICKHOUSE_USER=${AUTH_USER}
      - CLICKHOUSE_PASSWORD=${AUTH_PASSWORD}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  aptabase:
    container_name: aptabase_app
    image: ghcr.io/aptabase/aptabase:main
    restart: always
    depends_on:
      - aptabase_events_db
      - aptabase_db
    ports:
      - 9073:80
    networks:
      - aptabase
      - proxy
    environment:
      - BASE_URL=${BASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - DATABASE_URL=Server=aptabase_db;Port=5432;User Id=${AUTH_USER};Password=${AUTH_PASSWORD};Database=${AUTH_USER}
      - CLICKHOUSE_URL=Host=aptabase_events_db;Port=8123;Username=${AUTH_USER};Password=${AUTH_PASSWORD}

volumes:
  aptabase-db-data:
    driver: local
    external: true
  aptabase-events-db-data:
    driver: local
    external: true
networks:
  aptabase:
  proxy:
    external: true    
