version: "3.2"
services:
  aptabase_db:
    container_name: aptabase_db
    image: postgres:15-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: aptabase
      POSTGRES_PASSWORD: ePBcgYb3Zm9RKdm0jmcAdhBCajnPmz7j

  aptabase_events_db:
    container_name: aptabase_events_db
    image: clickhouse/clickhouse-server:23.8.4.69-alpine
    restart: always
    volumes:
      - events-db-data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_USER: aptabase
      CLICKHOUSE_PASSWORD: ePBcgYb3Zm9RKdm0jmcAdhBCajnPmz7j
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  aptabase:
    container_name: aptabase_app
    image: ghcr.io/aptabase/aptabase:main
    restart: always
    depends_on:
      - aptabase_events_db
      - aptabase_db
    ports:
      - 9073:80
    environment:
      BASE_URL: http://localhost:8000 # replace with your ip or domain, including port if needed
      AUTH_SECRET: Qz8kyeJ4ACS5iBRRTNuq7fu8w3oLYZll # get a strong secret from https://randomkeygen.com/
      DATABASE_URL: Server=aptabase_db;Port=5432;User Id=aptabase;Password=ePBcgYb3Zm9RKdm0jmcAdhBCajnPmz7j;Database=aptabase
      CLICKHOUSE_URL: Host=aptabase_events_db;Port=8123;Username=aptabase;Password=ePBcgYb3Zm9RKdm0jmcAdhBCajnPmz7j

volumes:
  db-data:
    driver: local
  events-db-data:
    driver: local
