version: "2"
services:
  ackee:
    image: electerious/ackee
    container_name: ackee
    restart: always
    environment:
      - WAIT_HOSTS=mongo:27017
    ports:
      - "9041:3000"
   depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./data:/data/db
