# Generated on Mon Jul  1 04:24:24 CEST 2024
# USE SSL: letsencrypt
version: "3.8"

x-restart-policy: &restart_policy
  restart: unless-stopped

x-defaults: &defaults
  <<: *restart_policy
  image: ghcr.io/tryzealot/zealot:latest
  depends_on:
    - postgres
  environment:
    - ZEALOT_DOMAIN=${ZEALOT_DOMAIN}
    - ZEALOT_CERT_EMAIL=${ZEALOT_CERT_EMAIL}
    - ZEALOT_ADMIN_EMAIL=${ZEALOT_ADMIN_EMAIL}
    - ZEALOT_ADMIN_PASSWORD=${ZEALOT_ADMIN_PASSWORD}
    - ZEALOT_GUEST_MODE=${ZEALOT_GUEST_MODE}
    - ZEALOT_REGISTER_ENABLED=${ZEALOT_REGISTER_ENABLED}
    - FEISHU_ENABLED=${FEISHU_ENABLED}
    - FEISHU_APP_ID=${FEISHU_APP_ID}
    - FEISHU_APP_SECRET=${FEISHU_APP_SECRET}
    - GITLAB_ENABLED=${GITLAB_ENABLED}
    - GITLAB_SITE=${GITLAB_SITE}
    - GITLAB_SCOPE=${GITLAB_SCOPE}
    - GITLAB_APP_ID=${GITLAB_APP_ID}
    - GITLAB_APP_SECRET=${GITLAB_APP_SECRET}
    - GOOGLE_OAUTH_ENABLED=${GOOGLE_OAUTH_ENABLED}
    - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    - GOOGLE_SECRET=${GOOGLE_SECRET}
    - LDAP_ENABLED=${LDAP_ENABLED}
    - LDAP_HOST=${LDAP_HOST}
    - LDAP_PORT=${LDAP_PORT}
    - LDAP_METHOD=${LDAP_METHOD}
    - LDAP_BIND_DN=${LDAP_BIND_DN}
    - LDAP_PASSWORD=${LDAP_PASSWORD}
    - LDAP_BASE=${LDAP_BASE}
    - LDAP_UID=${LDAP_UID}
    - SMTP_DOMAIN=${SMTP_DOMAIN}
    - SMTP_ADDRESS=${SMTP_ADDRESS}
    - SMTP_PORT=${SMTP_PORT}
    - SMTP_USERNAME=${SMTP_USERNAME}
    - SMTP_PASSWORD=${SMTP_PASSWORD}
    - SMTP_AUTH_METHOD=${SMTP_AUTH_METHOD}
    - SMTP_ENABLE_STARTTLS=${SMTP_ENABLE_STARTTLS}
    - ACTION_MAILER_DEFAULT_FROM=${ACTION_MAILER_DEFAULT_FROM}
    - ACTION_MAILER_DEFAULT_TO=${ACTION_MAILER_DEFAULT_TO}
    - GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID}
    - ZEALOT_SENTRY_DISABLE=${ZEALOT_SENTRY_DISABLE}
    - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
    - SECRET_TOKEN=${SECRET_TOKEN}
    - PUMA_CONTROL_URL=${PUMA_CONTROL_URL}
    - PUMA_CONTROL_PORT=${PUMA_CONTROL_PORT}
    - ZEALOT_POSTGRES_HOST=${ZEALOT_POSTGRES_HOST}
    - ZEALOT_POSTGRES_PORT=${ZEALOT_POSTGRES_PORT}
    - ZEALOT_POSTGRES_USERNAME=${ZEALOT_POSTGRES_USERNAME}
    - ZEALOT_POSTGRES_PASSWORD=${ZEALOT_POSTGRES_PASSWORD}
    - ZEALOT_POSTGRES_DB_NAME=${ZEALOT_POSTGRES_DB_NAME}
  volumes:
    - zealot-uploads:/app/public/uploads
    - zealot-backup:/app/public/backup
    - ./log:/app/log
  healthcheck:
    test: ["CMD-SHELL", "wget -q --spider --proxy=off localhost/health || exit 1"]
  logging:
    driver: "json-file"
    options:
      max-size: "1g"
      max-file: "10"
      max-buffer-size: "4m"
      mode: "non-blocking"

services:
  postgres:
    <<: *restart_policy
    image: postgres:14-alpine
    volumes:
      - zealot-postgres:/var/lib/postgresql/data
    # environment:
    #   POSTGRES_PASSWORD: ze@l0t
    environment:
      - POSTGRES_PASSWORD=${ZEALOT_POSTGRES_PASSWORD}
      - ZEALOT_DOMAIN=${ZEALOT_DOMAIN}
      - ZEALOT_CERT_EMAIL=${ZEALOT_CERT_EMAIL}
      - ZEALOT_ADMIN_EMAIL=${ZEALOT_ADMIN_EMAIL}
      - ZEALOT_ADMIN_PASSWORD=${ZEALOT_ADMIN_PASSWORD}
      - ZEALOT_GUEST_MODE=${ZEALOT_GUEST_MODE}
      - ZEALOT_REGISTER_ENABLED=${ZEALOT_REGISTER_ENABLED}
      - FEISHU_ENABLED=${FEISHU_ENABLED}
      - FEISHU_APP_ID=${FEISHU_APP_ID}
      - FEISHU_APP_SECRET=${FEISHU_APP_SECRET}
      - GITLAB_ENABLED=${GITLAB_ENABLED}
      - GITLAB_SITE=${GITLAB_SITE}
      - GITLAB_SCOPE=${GITLAB_SCOPE}
      - GITLAB_APP_ID=${GITLAB_APP_ID}
      - GITLAB_APP_SECRET=${GITLAB_APP_SECRET}
      - GOOGLE_OAUTH_ENABLED=${GOOGLE_OAUTH_ENABLED}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - LDAP_ENABLED=${LDAP_ENABLED}
      - LDAP_HOST=${LDAP_HOST}
      - LDAP_PORT=${LDAP_PORT}
      - LDAP_METHOD=${LDAP_METHOD}
      - LDAP_BIND_DN=${LDAP_BIND_DN}
      - LDAP_PASSWORD=${LDAP_PASSWORD}
      - LDAP_BASE=${LDAP_BASE}
      - LDAP_UID=${LDAP_UID}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - SMTP_ADDRESS=${SMTP_ADDRESS}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_AUTH_METHOD=${SMTP_AUTH_METHOD}
      - SMTP_ENABLE_STARTTLS=${SMTP_ENABLE_STARTTLS}
      - ACTION_MAILER_DEFAULT_FROM=${ACTION_MAILER_DEFAULT_FROM}
      - ACTION_MAILER_DEFAULT_TO=${ACTION_MAILER_DEFAULT_TO}
      - GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID}
      - ZEALOT_SENTRY_DISABLE=${ZEALOT_SENTRY_DISABLE}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - SECRET_TOKEN=${SECRET_TOKEN}
      - PUMA_CONTROL_URL=${PUMA_CONTROL_URL}
      - PUMA_CONTROL_PORT=${PUMA_CONTROL_PORT}
      - ZEALOT_POSTGRES_HOST=${ZEALOT_POSTGRES_HOST}
      - ZEALOT_POSTGRES_PORT=${ZEALOT_POSTGRES_PORT}
      - ZEALOT_POSTGRES_USERNAME=${ZEALOT_POSTGRES_USERNAME}
      - ZEALOT_POSTGRES_PASSWORD=${ZEALOT_POSTGRES_PASSWORD}
      - ZEALOT_POSTGRES_DB_NAME=${ZEALOT_POSTGRES_DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  zealot:
    <<: *defaults
  web:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/etc/caddy/certs:/etc/caddy/certs:ro
    env_file: .env
    environment:
      ACME_AGREE: "true"

volumes:
  zealot-uploads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .//zealot/uploads
  zealot-backup:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .//zealot/backup
  zealot-postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .//postgres
